timeout: 5400s

steps:
- name: 'europe-docker.pkg.dev/compute-image-osconfig-agent/osconfig-package-build-presubmit/osconfig-package-build-presubmit:latest'
  args: ["mahmoudn-vmm-dev", "europe-west4-a", "deb11,el8,el8_arm64,el9,el9_arm64,goo"]

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
